### ISSUE TITLE
efface de manière intermittente les informations

### ISSUE THREAD

**Issue by XecKiE** [ulzbug/Zdesigner#1]
J'ai eu le cas plusieurs fois: je fais mon schéma, je l'enregistre, je refais des modifications (comme l'ajout de clés étrangères), j'enregistre une nouvelle fois et pouf !... plus de clé étrangère !

Idem à la création du schéma: si on n'enregistre pas le nouveau schéma avant d'ajouter les clés étrangères, ca n'est pas enregistré.

Bref, pas très lunette de VC

**Comment by ulzbug** [comment]
C'est corrigé
