### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by XecKiE** [ulzbug/Zdesigner#3]
Dans le zdesigner on ne peut pas dézoomer, ce qui rend certains graphiques incompréhensible (pas possible d'avoir la vue d'ensemble).

Si on utilise la fonction intégrée du navigateur, ça "marche" pour les tables, mais les flèches sont complètements pétées. Il faudrait soit réparer ces flèches, soit ajouter une fonction de zoom/dezoom fluide.

**Comment by ulzbug** [comment]
C'est corrigé pour le zoom et pour le resize de fenêtre
